### PR TITLE
updated to CUBA 6.9; version 0.6.0

### PR DESCRIPTION
**Pull request by mariodavid**
Hi,

this PR updates the component to CUBA 6.9 and sets the release to 0.6.0.

Documentation is updated accordingly.

### CODE REVIEW

**Comment by mariodavid** [comment]
hi @bresche @alferink,

bumped version update. Feel free to merge!

Bye
Mario

**Comment by bresche** [comment]
thank you mario, I bumped it up :-)

**Comment by mariodavid** [comment]
thanks @bresche. Can you also release it on bintray? Then I can update my downstream dependency accordingly: https://github.com/mariodavid/cuba-component-data-import/issues/102

Thanks

**Comment by bresche** [comment]
I blew it up...

**Pull request merged**
